---
- name: stop httpd
  service: name=httpd state=stopped enabled=no

- name: remove apache
  yum: name=httpd state=absent

- name: install nginx
  yum: name=nginx state=present

- name: template nginx configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: ensure nginx is running
  service: name=nginx state=started

- name: allow nginx through firewall
  shell: "/sbin/iptables -A INPUT -p tcp -m tcp --dport {{es_safe_port | quote}} -j ACCEPT"

- name: make iptables configuration peristent
  shell: /sbin/iptables-save
  notify:
    - restart iptables
