---
- name: install apache
  yum: name=httpd state=latest

- name: template apache configuration file
  template: src=httpd.conf.j2 dest=/etc/httpd/conf.d/elasticsearch.conf
  notify:
    - restart apache

- name: ensure apache is running
  service: name=httpd state=started
