---
- name: install apache
  yum: name=httpd state=latest

- name: template apache configuration file
  template: src=elasticsearch.conf.j2 dest=/etc/httpd/conf.d/elasticsearch.conf
  notify:
    - restart apache

- name: ensure apache is running
  service: name=httpd state=started

- name: allow apache through firewall
  shell: "/sbin/iptables -A INPUT -p tcp -m tcp --dport {{es_safe_port}} -j ACCEPT"

- name: make iptables configuration peristent
  shell: /sbin/iptables-save
  notify:
    - restart iptables
