---
- name:
  sudo: yes
  hosts: all
  roles:
    - common

- name: deploy elasticsearch cluster
  sudo: yes
  hosts: elasticsearch
  roles:
    - java
    - elasticsearch

- name: set up cron backup on the master nodes
  sudo: yes
  hosts: masters
  roles:
    - cron

- name: deploy nginx on web server
  sudo: yes
  hosts: web
  roles:
    - nginx
