---
- name: Deploy an Elasticsearch Cluster
  sudo: yes
  hosts: all
  roles:
    - common
    - java
    - elasticsearch
    # - iptables
    
- name: Deploy nginx on the master nodes
  sudo: yes
  hosts: masters
  roles:
    - cron
    - nginx
