---
- name: set up proxy and update all machines
  sudo: yes
  hosts: all
  roles:
    - proxy
    - update

- name: deploy elasticsearch cluster
  sudo: yes
  hosts: elasticsearch
  roles:
    - java
    - elasticsearch

- name: set up elasticsearch backup with cron on the master nodes
  sudo: yes
  hosts: masters
  roles:
    - elasticsearch-plugins
    - elasticsearch-backup

- name: deploy reverse proxy for elasticsearch
  sudo: yes
  hosts: reverse-proxy
  roles:
    - nginx
