---
- name: allow elasticsearch through firewall
  command: /sbin/iptables -A INPUT -p tcp -m tcp --dport {{ es_port }}:{{ es_max_port }} -j ACCEPT

- name: make iptables configuration peristent
  shell: /sbin/iptables-save
  notify:
    - restart iptables
